spring:
  datasource:
    username: xbox2537
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://josthis-db1.cplifuxv1ysv.ap-northeast-2.rds.amazonaws.com:3306/josthis

  jpa:
    hibernate:
      ddl-auto: none # !!!!!!!!!!!!
    database-platform: org.hibernate.dialect.MariaDB106Dialect

logging:
  level:
    sql: debug
